import { Role, Permission, User } from '../types';

export const ROLE_DEFAULT_PERMISSIONS: Record<Role, Permission[]> = {
  Owner: [
    'dashboard.view',
    'pos.access',
    'orders.view',
    'orders.create',
    'orders.edit',
    'orders.cancel',
    'orders.approve_cancellation',
    'tables.view',
    'tables.create',
    'tables.edit',
    'tables.delete',
    'reservations.view',
    'reservations.create',
    'reservations.edit',
    'reservations.delete',
    'customers.view',
    'customers.create',
    'customers.edit',
    'menu.view',
    'menu.create',
    'menu.edit',
    'menu.delete',
    'menu.change_price',
    'menu.change_availability',
    'kds.view',
    'kds.manage',
    'payments.view',
    'payments.create',
    'payments.refund',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.adjust',
    'inventory.wastage',
    'purchasing.view',
    'purchasing.manage',
    'delivery.view',
    'delivery.assign',
    'delivery.update',
    'loyalty.view',
    'loyalty.manage',
    'marketing.view',
    'marketing.manage',
    'staff.view',
    'staff.create',
    'staff.edit',
    'staff.delete',
    'branches.view',
    'branches.create',
    'branches.edit',
    'branches.delete',
    'reports.view',
    'reports.export',
    'audit.view',
    'backup.create',
    'backup.restore',
    'settings.view',
    'settings.edit',
  ],

  'Super Admin': [
    'dashboard.view',
    'pos.access',
    'orders.view',
    'orders.approve_cancellation',
    'tables.view',
    'tables.create',
    'tables.edit',
    'tables.delete',
    'customers.view',
    'menu.view',
    'menu.create',
    'menu.edit',
    'menu.delete',
    'menu.change_price',
    'menu.change_availability',
    'kds.view',
    'payments.view',
    'inventory.view',
    'purchasing.view',
    'staff.view',
    'staff.create',
    'staff.edit',
    'staff.delete',
    'branches.view',
    'branches.create',
    'branches.edit',
    'branches.delete',
    'reports.view',
    'reports.export',
    'audit.view',
    'backup.create',
    'backup.restore',
    'settings.view',
    'settings.edit',
  ],

  'Branch Manager': [
    'dashboard.view',
    'pos.access',
    'orders.view',
    'orders.create',
    'orders.edit',
    'orders.cancel',
    'orders.approve_cancellation',
    'tables.view',
    'tables.create',
    'tables.edit',
    'tables.delete',
    'reservations.view',
    'reservations.create',
    'reservations.edit',
    'reservations.delete',
    'customers.view',
    'customers.create',
    'customers.edit',
    'menu.view',
    'menu.create',
    'menu.edit',
    'menu.change_price',
    'menu.change_availability',
    'kds.view',
    'kds.manage',
    'payments.view',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.adjust',
    'inventory.wastage',
    'purchasing.view',
    'purchasing.manage',
    'delivery.view',
    'delivery.assign',
    'delivery.update',
    'loyalty.view',
    'marketing.view',
    'marketing.manage',
    'staff.view',
    'staff.create',
    'staff.edit',
    'reports.view',
    'reports.export',
    'audit.view',
  ],

  Accountant: [
    'dashboard.view',
    'orders.view',
    'payments.view',
    'reports.view',
    'reports.export',
  ],

  Cashier: [
    'pos.access',
    'orders.view',
    'payments.view',
    'payments.create',
    'payments.refund',
  ],

  'Order Taker': [
    'dashboard.view',
    'pos.access',
    'orders.view',
    'orders.create',
    'orders.edit',
    'orders.cancel',
    'tables.view',
    'tables.edit',
    'reservations.view',
    'reservations.create',
    'reservations.edit',
    'customers.view',
    'customers.create',
    'delivery.view',
    'delivery.assign',
  ],

  'Head Chef': [
    'kds.view',
    'kds.manage',
    'menu.view',
    'menu.change_availability',
    'inventory.view',
  ],

  'Kitchen Staff': [
    'kds.view',
    'kds.manage',
  ],

  'Inventory Manager': [
    'dashboard.view',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.adjust',
    'inventory.wastage',
    'purchasing.view',
    'purchasing.manage',
    'reports.view',
    'reports.export',
  ],

  'Staff Manager': [
    'staff.view',
    'staff.create',
    'staff.edit',
  ],

  Marketer: [
    'marketing.view',
    'marketing.manage',
    'loyalty.view',
    'loyalty.manage',
    'customers.view',
  ],

  'Graphic Designer': [
    'menu.view',
    'marketing.view',
  ],

  'Delivery Staff': [
    'delivery.view',
    'delivery.update',
  ],
};

export function hasPermission(user: User, permission: Permission): boolean {
  if (!user || !user.active) return false;

  // Individual override takes precedence
  if (user.permissionOverrides && user.permissionOverrides[permission] !== undefined) {
    return !!user.permissionOverrides[permission];
  }

  // Check role default
  const rolePermissions = ROLE_DEFAULT_PERMISSIONS[user.role] || [];
  return rolePermissions.includes(permission);
}

export function canAccessBranch(user: User, branchId: string): boolean {
  if (!user || !user.active) return false;
  if (user.role === 'Owner' || user.role === 'Super Admin') return true;
  return user.branchId === branchId;
}
